/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FORMULARIOS;
import MAIN.Principal;
import CLASES.Cliente;
import CLASES.Pedido;
import CLASES.Producto;
import java.awt.Color;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author sofia
 */
public class Frm_Cajero extends javax.swing.JFrame {
    DefaultTableModel modeloTablaPedidos;
    DefaultTableModel modeloTablaClientes;
    DefaultTableModel tablaProductos;
    /**
     * Creates new form Frm_InicioSesion_Cajero
     */
    public Frm_Cajero() {
        initComponents();
        this.setLocationRelativeTo(this);
        modeloTablaPedidos = (DefaultTableModel) TablaPedidos.getModel();
        cargarPedidos();
      
        cargarComboProductos();
         jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"Efectivo", "Tarjeta", "Yape", "Plin"}));
           cargarProductos();
         modeloTablaClientes=(DefaultTableModel) TablaClientes.getModel();
         
         jComboBox3.addActionListener(new java.awt.event.ActionListener() {
    public void actionPerformed(java.awt.event.ActionEvent evt) {
        actualizarPrecio(); // método para mostrar el precio al seleccionar producto
    }
});
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
      private void cargarPedidos() {
        modeloTablaPedidos.setRowCount(0);
        for (Pedido p : Principal.listaPedidos) {
            modeloTablaPedidos.addRow(new Object[]{
                
                p.getProducto(),
                p.getTotal()
               
            });
        }
    }
      private void actualizarPrecio() {
    String nombreSeleccionado = jComboBox3.getSelectedItem().toString();

    for (Producto p : Principal.listaProductos) {
        if (p.getNombre().equalsIgnoreCase(nombreSeleccionado)) {
            txtPrecio.setText(String.valueOf(p.getPrecio()));
            break;
        }
    }
}

      private void cargarComboProductos() {
    jComboBox3.removeAllItems(); // Limpia items previos

    for (Producto p : Principal.listaProductos) {
        jComboBox3.addItem(p.getNombre()); // Agrega el nombre de cada producto
    }
}
      private void cargarClientes()
      {
           modeloTablaClientes.setRowCount(0);
        for (Cliente c : Principal.listaClientes) {
            modeloTablaClientes.addRow(new Object[]{
                c.getDNI(),
                c.getNombreCliente()
                
               
            });
        }
      }
        private void registrarPedido() {
       String cliente = txtcliente.getText();
    String producto = jComboBox3.getSelectedItem().toString();
    String tipoPago = jComboBox1.getSelectedItem().toString();
    String totalStr = txtPrecio.getText();


    if (cliente.isEmpty() || producto.isEmpty() || totalStr.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Complete todos los campos");
        return;
    }

    double total;
    try {
        total = Double.parseDouble(totalStr);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Ingrese un total válido");
        return;
    }

    Pedido nuevo = new Pedido(cliente, producto, tipoPago, total);
    Principal.listaPedidos.add(nuevo);

    JOptionPane.showMessageDialog(null, "Pedido registrado correctamente");
    cargarPedidos();
        
    }

    private void buscarProducto() {
     String nombreBuscar = jComboBox3.getSelectedItem().toString();
    boolean encontrado = false;

    for (Producto p : Principal.listaProductos) {
        if (p.getNombre().equalsIgnoreCase(nombreBuscar)) {
            txtPrecio.setText(String.valueOf(p.getPrecio())); // muestra precio en JTextField
            encontrado = true;
            break;
        }
    }

    if (!encontrado) {
        JOptionPane.showMessageDialog(this, "Producto no encontrado.");
        txtPrecio.setText("");
    }
}
private void buscarCliente()
{
      String dniBuscado = txtcliente.getText();
    boolean encontrado = false;

    for (Cliente c : Principal.listaClientes) {
        if (c.getDNI().equals(dniBuscado)) {
            JOptionPane.showMessageDialog(this, "Cliente ya registrado: " + c.getNombreCliente());
            encontrado = true;
            break;
        }
    }

    if (!encontrado) {
        JOptionPane.showMessageDialog(this, "Cliente no encontrado");
    }
}

private void cargarProductos() {
    tablaProductos = (DefaultTableModel) TablaProductos.getModel();
    tablaProductos.setRowCount(0);

    for (Producto p : Principal.listaProductos) {
        tablaProductos.addRow(new Object[]{
            p.getNombre(),
            p.getPrecio()
        });
    }
}
private void registrarCliente()
{
     String dni = JOptionPane.showInputDialog(this, "Ingrese DNI del cliente:");
    if (dni == null || dni.trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "DNI no válido");
        return;
    }

    String nombre = JOptionPane.showInputDialog(this, "Ingrese nombre del cliente:");
    if (nombre == null || nombre.trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Nombre no válido");
        return;
    }

    // Verificar si ya existe el cliente con ese DNI
    for (Cliente c : Principal.listaClientes) {
        if (c.getDNI().equals(dni)) {
            JOptionPane.showMessageDialog(this, "El cliente ya está registrado");
            return;
        }
    }

    Cliente nuevo = new Cliente(dni, nombre);
    Principal.listaClientes.add(nuevo);
    JOptionPane.showMessageDialog(this, "Cliente registrado correctamente");
    cargarClientes();
}

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        Panel_Pedidos = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtcliente = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaProductos = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton9 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        TablaPedidos = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        TablaClientes = new javax.swing.JTable();
        jButton11 = new javax.swing.JButton();
        jComboBox3 = new javax.swing.JComboBox<>();
        txtPrecio = new javax.swing.JTextField();
        Enviar_Comprobantes = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton10 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 2));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Bienvenido(a) a");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("Starbucks Cajero");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 150, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 102, 102));
        jButton1.setText("Pedidos");
        jButton1.setBorder(null);
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 102, 102));
        jButton2.setText("Enviar Comprobantes");
        jButton2.setBorder(null);
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 150, -1));

        jButton3.setBackground(new java.awt.Color(0, 102, 102));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Cerrar Sesión");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 440));

        Panel_Pedidos.setBackground(new java.awt.Color(255, 255, 255));
        Panel_Pedidos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("PEDIDOS");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        Panel_Pedidos.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 50));

        jLabel5.setText("DNI  del Cliente :");
        Panel_Pedidos.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 100, -1));
        Panel_Pedidos.add(txtcliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 140, -1));

        jLabel6.setText("Producto :");
        Panel_Pedidos.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 70, -1));

        jLabel7.setText("Precio :");
        Panel_Pedidos.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 70, -1));

        jButton4.setBackground(new java.awt.Color(0, 102, 102));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Registrar Pedido");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        Panel_Pedidos.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 220, -1, -1));

        TablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Producto", "Precio"
            }
        ));
        jScrollPane1.setViewportView(TablaProductos);

        Panel_Pedidos.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 270, 270, 150));

        jLabel17.setText("Tipo de Pago :");
        Panel_Pedidos.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 80, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Panel_Pedidos.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 140, -1));

        jButton9.setBackground(new java.awt.Color(0, 102, 102));
        jButton9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("Buscar cliente");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        Panel_Pedidos.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, -1, -1));

        TablaPedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Producto", "Precio"
            }
        ));
        jScrollPane3.setViewportView(TablaPedidos);

        Panel_Pedidos.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, 400, 150));

        TablaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "DNI", "Cliente"
            }
        ));
        jScrollPane4.setViewportView(TablaClientes);

        Panel_Pedidos.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 270, 150));

        jButton11.setBackground(new java.awt.Color(0, 102, 102));
        jButton11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton11.setForeground(new java.awt.Color(255, 255, 255));
        jButton11.setText("Registrar cliente");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        Panel_Pedidos.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 440, -1, -1));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Panel_Pedidos.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 140, -1));
        Panel_Pedidos.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 140, -1));

        jPanel1.add(Panel_Pedidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 740, 480));
        Panel_Pedidos.getAccessibleContext().setAccessibleDescription("");

        Enviar_Comprobantes.setBackground(new java.awt.Color(255, 255, 255));
        Enviar_Comprobantes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(0, 102, 102));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ENVIAR COMPROBANTES");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        Enviar_Comprobantes.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1400, 60));

        jButton5.setBackground(new java.awt.Color(0, 102, 102));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Emitir comprobante");
        Enviar_Comprobantes.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 460, -1, -1));

        jLabel9.setText("Total :");
        Enviar_Comprobantes.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, -1, -1));
        Enviar_Comprobantes.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 140, -1));

        jLabel10.setText("Nombre :");
        Enviar_Comprobantes.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, -1, -1));
        Enviar_Comprobantes.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 130, -1));

        jLabel11.setText("Apellido :");
        Enviar_Comprobantes.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, -1));
        Enviar_Comprobantes.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 130, -1));

        jLabel12.setText("DNI o RUC :");
        Enviar_Comprobantes.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, -1, -1));
        Enviar_Comprobantes.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 130, -1));

        jLabel13.setText("Tipo de comprobante :");
        Enviar_Comprobantes.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Enviar_Comprobantes.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 130, -1));

        jLabel14.setText("Fecha de emisión :");
        Enviar_Comprobantes.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));
        Enviar_Comprobantes.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 130, -1));

        jLabel15.setText("IGV :");
        Enviar_Comprobantes.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, -1, -1));
        Enviar_Comprobantes.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 400, 140, -1));

        jLabel16.setText("Subtotal :");
        Enviar_Comprobantes.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, -1, -1));
        Enviar_Comprobantes.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 140, -1));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Apellido", "DNI o RUC", "Tipo de comprobante", "Fecha", "Total", "Subtotal", "IGV"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        Enviar_Comprobantes.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, 720, 340));

        jButton10.setBackground(new java.awt.Color(0, 102, 102));
        jButton10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setText("Enviar comprobante");
        Enviar_Comprobantes.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 450, 160, -1));

        jPanel1.add(Enviar_Comprobantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(1400, 600, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Principal.pantallaPrincipal.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // BOTON REGISTRAR  PEDIDO
       registrarPedido();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // BOTON BUSCAR CLIENTE
        buscarCliente();
    }//GEN-LAST:event_jButton9ActionPerformed
    
    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // BOTON REGISTRAR CLIENTE
         registrarCliente();
    }//GEN-LAST:event_jButton11ActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_Cajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_Cajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_Cajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_Cajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_Cajero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Enviar_Comprobantes;
    private javax.swing.JPanel Panel_Pedidos;
    private javax.swing.JTable TablaClientes;
    private javax.swing.JTable TablaPedidos;
    private javax.swing.JTable TablaProductos;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtcliente;
    // End of variables declaration//GEN-END:variables
}
