/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FORMULARIOS;
import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JPanel;

import MAIN.Principal;
/**
 *
 * @author nobody
 */
public class Frm_InicioSesion extends javax.swing.JFrame {
    
    /**
     * Creates new form INICIO_SESION_GERENTE
     */
    public Frm_InicioSesion() {
        initComponents();
        this.setLocationRelativeTo(this);
        JButton[] botones = {
            btn_Ordenes,
            btn_Inventario,
            btn_Reclamos,
            btn_Horarios,
            btn_Usuarios,
            btn_Menu,
            btn_Clientes
        };
        for (JButton btn : botones) {
            btn.setOpaque(true);
            btn.setBackground(Color.WHITE);
        }
        this.setSize(1000,600);
        this.setLocationRelativeTo(null);
    }
    final boolean[] isPressed = new boolean[7];
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btn_Cerrar = new javax.swing.JButton();
        btn_Ordenes = new javax.swing.JButton();
        btn_Inventario = new javax.swing.JButton();
        btn_Clientes = new javax.swing.JButton();
        btn_Menu = new javax.swing.JButton();
        btn_Reclamos = new javax.swing.JButton();
        btn_Horarios = new javax.swing.JButton();
        btn_Usuarios = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Panel_Inventario = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        Panel_Ordenes = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        Panel_Reclamos = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        Panel_Horarios = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        Panel_Usuarios = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        Panel_Menu = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        Panel_Clientes = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel15 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("INICIO_SESION_GERENTE");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 2));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_Cerrar.setForeground(new java.awt.Color(30, 57, 50));
        btn_Cerrar.setText("Cerrar Sesión");
        btn_Cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CerrarActionPerformed(evt);
            }
        });
        jPanel2.add(btn_Cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, -1, -1));

        btn_Ordenes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_Ordenes.setForeground(new java.awt.Color(0, 89, 102));
        btn_Ordenes.setText("Ordenes");
        btn_Ordenes.setBorder(null);
        btn_Ordenes.setBorderPainted(false);
        btn_Ordenes.setContentAreaFilled(false);
        btn_Ordenes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_Ordenes.setDefaultCapable(false);
        btn_Ordenes.setFocusCycleRoot(true);
        btn_Ordenes.setFocusPainted(false);
        btn_Ordenes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_Ordenes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_OrdenesActionPerformed(evt);
            }
        });
        jPanel2.add(btn_Ordenes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 160, 30));
        //Main

        btn_Inventario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_Inventario.setForeground(new java.awt.Color(0, 89, 102));
        btn_Inventario.setText("Inventario");
        btn_Inventario.setBorder(null);
        btn_Inventario.setBorderPainted(false);
        btn_Inventario.setContentAreaFilled(false);
        btn_Inventario.setDefaultCapable(false);
        btn_Inventario.setFocusCycleRoot(true);
        btn_Inventario.setFocusPainted(false);
        btn_Inventario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_Inventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_InventarioActionPerformed(evt);
            }
        });
        jPanel2.add(btn_Inventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 160, 30));

        btn_Clientes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_Clientes.setForeground(new java.awt.Color(0, 89, 102));
        btn_Clientes.setText("Clientes");
        btn_Clientes.setBorder(null);
        btn_Clientes.setBorderPainted(false);
        btn_Clientes.setContentAreaFilled(false);
        btn_Clientes.setDefaultCapable(false);
        btn_Clientes.setFocusCycleRoot(true);
        btn_Clientes.setFocusPainted(false);
        btn_Clientes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_Clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ClientesActionPerformed(evt);
            }
        });
        jPanel2.add(btn_Clientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 160, 30));

        btn_Menu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_Menu.setForeground(new java.awt.Color(0, 89, 102));
        btn_Menu.setText("Menú");
        btn_Menu.setBorder(null);
        btn_Menu.setBorderPainted(false);
        btn_Menu.setContentAreaFilled(false);
        btn_Menu.setDefaultCapable(false);
        btn_Menu.setFocusCycleRoot(true);
        btn_Menu.setFocusPainted(false);
        btn_Menu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MenuActionPerformed(evt);
            }
        });
        jPanel2.add(btn_Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 160, 30));

        btn_Reclamos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_Reclamos.setForeground(new java.awt.Color(0, 89, 102));
        btn_Reclamos.setText("Registro de Reclamos");
        btn_Reclamos.setBorder(null);
        btn_Reclamos.setBorderPainted(false);
        btn_Reclamos.setContentAreaFilled(false);
        btn_Reclamos.setDefaultCapable(false);
        btn_Reclamos.setFocusCycleRoot(true);
        btn_Reclamos.setFocusPainted(false);
        btn_Reclamos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_Reclamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ReclamosActionPerformed(evt);
            }
        });
        jPanel2.add(btn_Reclamos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 160, 30));

        btn_Horarios.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_Horarios.setForeground(new java.awt.Color(0, 89, 102));
        btn_Horarios.setText("Turnos y Horarios");
        btn_Horarios.setBorder(null);
        btn_Horarios.setBorderPainted(false);
        btn_Horarios.setContentAreaFilled(false);
        btn_Horarios.setDefaultCapable(false);
        btn_Horarios.setFocusCycleRoot(true);
        btn_Horarios.setFocusPainted(false);
        btn_Horarios.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_Horarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_HorariosActionPerformed(evt);
            }
        });
        jPanel2.add(btn_Horarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 160, 30));

        btn_Usuarios.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_Usuarios.setForeground(new java.awt.Color(0, 89, 102));
        btn_Usuarios.setText("Usuarios");
        btn_Usuarios.setBorder(null);
        btn_Usuarios.setBorderPainted(false);
        btn_Usuarios.setContentAreaFilled(false);
        btn_Usuarios.setDefaultCapable(false);
        btn_Usuarios.setFocusCycleRoot(true);
        btn_Usuarios.setFocusPainted(false);
        btn_Usuarios.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_Usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_UsuariosActionPerformed(evt);
            }
        });
        jPanel2.add(btn_Usuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 160, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 89, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Starbucks Gerente");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 190, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 89, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Bienvenido(a) a");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 190, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 510));

        Panel_Inventario.setFocusCycleRoot(true);
        Panel_Inventario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("INVENTARIO");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 12, 640, 40));

        Panel_Inventario.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 60));

        jPanel4.setBackground(new java.awt.Color(255, 252, 242));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        Panel_Inventario.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 650, 420));

        jPanel1.add(Panel_Inventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 650, 480));

        Panel_Ordenes.setFocusCycleRoot(true);
        Panel_Ordenes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(0, 102, 102));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ORDENES");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 12, 660, 40));

        Panel_Ordenes.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 60));

        jPanel6.setBackground(new java.awt.Color(255, 252, 242));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        Panel_Ordenes.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 680, 450));

        jPanel1.add(Panel_Ordenes, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 650, 480));

        Panel_Reclamos.setFocusCycleRoot(true);
        Panel_Reclamos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(0, 102, 102));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("RECLAMOS");
        jPanel7.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 12, 660, 40));

        Panel_Reclamos.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 60));

        jPanel8.setBackground(new java.awt.Color(255, 252, 242));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        Panel_Reclamos.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 680, 450));

        jPanel1.add(Panel_Reclamos, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 650, 480));

        Panel_Horarios.setFocusCycleRoot(true);
        Panel_Horarios.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setBackground(new java.awt.Color(0, 102, 102));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("HORARIOS");
        jPanel9.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 12, 660, 40));

        Panel_Horarios.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 60));

        jPanel10.setBackground(new java.awt.Color(255, 252, 242));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        Panel_Horarios.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 680, 450));

        jPanel1.add(Panel_Horarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 650, 480));

        Panel_Usuarios.setFocusCycleRoot(true);
        Panel_Usuarios.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel11.setBackground(new java.awt.Color(0, 102, 102));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("USUARIOS");
        jPanel11.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 12, 660, 40));

        Panel_Usuarios.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 60));

        jPanel12.setBackground(new java.awt.Color(255, 252, 242));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        Panel_Usuarios.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 680, 450));

        jPanel1.add(Panel_Usuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 650, 480));

        Panel_Menu.setFocusCycleRoot(true);
        Panel_Menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel13.setBackground(new java.awt.Color(0, 102, 102));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("MENÚ");
        jPanel13.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 12, 660, 40));

        Panel_Menu.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 60));

        jPanel14.setBackground(new java.awt.Color(255, 252, 242));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        Panel_Menu.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 680, 450));

        jPanel1.add(Panel_Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 650, 480));

        Panel_Clientes.setFocusCycleRoot(true);
        Panel_Clientes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel15.setBackground(new java.awt.Color(0, 102, 102));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("CLIENTES");
        jPanel15.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 12, 660, 40));

        Panel_Clientes.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 60));

        jPanel16.setBackground(new java.awt.Color(255, 252, 242));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Apellido", "Telefono", "Dirección", "Género", "Fec_Nac"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel16.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 380, 230));

        jLabel3.setText("Nombre:");
        jPanel16.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, -1, -1));
        jPanel16.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 50, 120, -1));

        jLabel11.setText("Apellido:");
        jPanel16.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, -1, -1));
        jPanel16.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 100, 120, -1));

        jLabel12.setText("Telefono:");
        jPanel16.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 150, -1, -1));
        jPanel16.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 150, 120, -1));

        jLabel13.setText("Dirección:");
        jPanel16.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 210, -1, -1));
        jPanel16.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 200, 120, -1));

        jLabel14.setText("Género:");
        jPanel16.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 270, -1, -1));

        jRadioButton1.setText("Femenino");
        jPanel16.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 270, -1, -1));

        jRadioButton2.setText("Masculino");
        jPanel16.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 270, -1, -1));

        jLabel15.setText("Fec_Nac:");
        jPanel16.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 330, -1, -1));
        jPanel16.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 330, 130, -1));

        jButton1.setText("Registrar");
        jPanel16.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        jButton2.setText("Modificar");
        jPanel16.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, -1, -1));

        jButton3.setText("Limpiar");
        jPanel16.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, -1, -1));

        jButton4.setText("Eliminar");
        jPanel16.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, -1, -1));

        Panel_Clientes.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 720, 460));

        jPanel1.add(Panel_Clientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 1400, 480));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_InventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_InventarioActionPerformed
        BotonPresionado(btn_Inventario,new Color(243,247,237), isPressed, 1);
        activarUno(isPressed,1);
        System.out.println("Boton Inventario presionado");
    }//GEN-LAST:event_btn_InventarioActionPerformed

    private void btn_OrdenesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_OrdenesActionPerformed
        BotonPresionado(btn_Ordenes,new Color(243,247,237), isPressed, 0);
        activarUno(isPressed,0);
        System.out.println("Boton Ordenes presionado");
    }//GEN-LAST:event_btn_OrdenesActionPerformed

    private void btn_ReclamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ReclamosActionPerformed
        BotonPresionado(btn_Reclamos,new Color(243,247,237), isPressed, 2);
        activarUno(isPressed,2);
        System.out.println("Boton Reclamos presionado");
    }//GEN-LAST:event_btn_ReclamosActionPerformed

    private void btn_HorariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_HorariosActionPerformed
        BotonPresionado(btn_Horarios,new Color(243,247,237), isPressed, 3);
        activarUno(isPressed,3);
        System.out.println("Boton Horarios presionado");
    }//GEN-LAST:event_btn_HorariosActionPerformed

    private void btn_UsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_UsuariosActionPerformed
        BotonPresionado(btn_Usuarios,new Color(243,247,237), isPressed, 4);
        activarUno(isPressed,4);
        System.out.println("Boton Usuarios presionado");

    }//GEN-LAST:event_btn_UsuariosActionPerformed

    private void btn_MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MenuActionPerformed
        BotonPresionado(btn_Menu,new Color(243,247,237), isPressed, 5);
        activarUno(isPressed,5);
        System.out.println("Boton Menu presionado");
    }//GEN-LAST:event_btn_MenuActionPerformed

    private void btn_ClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ClientesActionPerformed
        BotonPresionado(btn_Clientes,new Color(243,247,237), isPressed, 6);
        activarUno(isPressed,6);
        System.out.println("Boton Clientes presionado");
    }//GEN-LAST:event_btn_ClientesActionPerformed

    private void btn_CerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CerrarActionPerformed
        this.dispose();
        Principal.pantallaPrincipal.setVisible(true);
    }//GEN-LAST:event_btn_CerrarActionPerformed

    public void BotonPresionado(JButton boton, Color color, boolean[] isPressed, int array){
        isPressed[array] = true;
        boton.setBackground(color);
    }
    public void activarUno(boolean[] estados, int indiceActivo){
        JButton[] botones = {
            btn_Ordenes,
            btn_Inventario,
            btn_Reclamos,
            btn_Horarios,
            btn_Usuarios,
            btn_Menu,
            btn_Clientes
        };
        JPanel[] paneles = {
            Panel_Ordenes,
            Panel_Inventario,
            Panel_Reclamos,
            Panel_Horarios,
            Panel_Usuarios,
            Panel_Menu,
            Panel_Clientes
        };
        for(int i = 0;i<estados.length;i++){
            if(i == indiceActivo){
                estados[i] = (i== indiceActivo);
                paneles[i].setVisible(true);
            }else{
                estados[i] = false;
                botones[i].setBackground(Color.WHITE);
                paneles[i].setVisible(false);
            }
            
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel_Clientes;
    private javax.swing.JPanel Panel_Horarios;
    private javax.swing.JPanel Panel_Inventario;
    private javax.swing.JPanel Panel_Menu;
    private javax.swing.JPanel Panel_Ordenes;
    private javax.swing.JPanel Panel_Reclamos;
    private javax.swing.JPanel Panel_Usuarios;
    private javax.swing.JButton btn_Cerrar;
    private javax.swing.JButton btn_Clientes;
    private javax.swing.JButton btn_Horarios;
    private javax.swing.JButton btn_Inventario;
    private javax.swing.JButton btn_Menu;
    private javax.swing.JButton btn_Ordenes;
    private javax.swing.JButton btn_Reclamos;
    private javax.swing.JButton btn_Usuarios;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
