/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FORMULARIOS;

import java.awt.Color;
import MAIN.Principal;
import CLASES.Usuario;
import javax.swing.JOptionPane;
/**
 *
 * @author nobody
 */
public class Frm_Principal extends javax.swing.JFrame {

    /**
     * Creates new form MENÚ_PRINCIPAL
     */
    
    public Frm_Principal() {
        initComponents();
        this.setLocationRelativeTo(this);
        btn_Iniciar.putClientProperty("JComponent.roundRect", true);
        btn_Iniciar.setOpaque(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Imagen1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        txt_Contrasena = new javax.swing.JTextField();
        txt_Correo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btn_Iniciar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setToolTipText("");
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Imagen1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Paquete/Starbucks_Logo.png"))); // NOI18N
        jPanel2.add(Imagen1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 90));

        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 440, -1, -1));

        txt_Contrasena.setForeground(new java.awt.Color(204, 204, 204));
        txt_Contrasena.setText("*******");
        txt_Contrasena.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Contraseña", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));
        txt_Contrasena.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_ContrasenaMousePressed(evt);
            }
        });
        jPanel2.add(txt_Contrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 280, 50));

        txt_Correo.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Correo Electronico", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));
        jPanel2.add(txt_Correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 280, 50));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Iniciar sesión");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, -1, -1));

        btn_Iniciar.setBackground(new java.awt.Color(0, 98, 65));
        btn_Iniciar.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        btn_Iniciar.setForeground(new java.awt.Color(255, 255, 255));
        btn_Iniciar.setText("Iniciar Sesión");
        btn_Iniciar.setBorder(null);
        btn_Iniciar.setBorderPainted(false);
        btn_Iniciar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_Iniciar.setDefaultCapable(false);
        btn_Iniciar.setFocusCycleRoot(true);
        btn_Iniciar.setFocusPainted(false);
        btn_Iniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_IniciarActionPerformed(evt);
            }
        });
        jPanel2.add(btn_Iniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 170, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 470));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txt_ContrasenaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_ContrasenaMousePressed
        txt_Contrasena.setText("");
        txt_Contrasena.setForeground(Color.black);
    }//GEN-LAST:event_txt_ContrasenaMousePressed

    private void btn_IniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_IniciarActionPerformed
        String correoIngresado = txt_Correo.getText();  
        String contrasenaIngresada = txt_Contrasena.getText();
        
        boolean accesoConcedido = false;
        
        for (Usuario u : Principal.listaUsuarios){
            if(u.getCorreo().equals(correoIngresado) && u.getContrasena().equals(contrasenaIngresada)){
                System.out.print("Encontrado");
                accesoConcedido = true;
                if(u.getRol().equals("Encargado")){
                    Principal.pantallaEncargado.setVisible(true);                   
                }else if(u.getRol().equals("Gerente")){
                    Principal.pantallaGerente.setVisible(true);  
                }else if(u.getRol().equals("Cajero")){
                    Principal.pantallaCajero.setVisible(true);
                }else if(u.getRol().equals("Supervisor")){
                }
                this.setVisible(false);
            }
        }
        System.out.print("No encontrado");
        if(!accesoConcedido){
            JOptionPane.showMessageDialog(this,"Correo o contraseña incorrecta");
        }
    }//GEN-LAST:event_btn_IniciarActionPerformed
  
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Imagen1;
    private javax.swing.JButton btn_Iniciar;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txt_Contrasena;
    private javax.swing.JTextField txt_Correo;
    // End of variables declaration//GEN-END:variables
}
