/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FORMULARIOS;
import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JPanel;

import MAIN.Principal;
import CLASES.Reclamo;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author nobody
 */
public class Frm_Gerente extends javax.swing.JFrame {
    DefaultTableModel modeloTabla;
    /**
     * Creates new form INICIO_SESION_GERENTE
     */
    public Frm_Gerente() {
        initComponents();
        this.setLocationRelativeTo(this);
        modeloTabla = (DefaultTableModel) tabla_reclamos.getModel();
        Reclamo prueba = new Reclamo("R001", "Juan Pérez", "2025-06-20", "Producto en mal estado", "El café llegó derramado y con la tapa rota.");
        Principal.listaReclamos.add(prueba);
        
        cargarReclamos();
        JButton[] botones = {
            btn_Ordenes,
          
            btn_Reclamos,
            btn_Horarios,
           
            btn_Menu,
            
        };
        for (JButton btn : botones) {
            btn.setOpaque(true);
            btn.setBackground(Color.WHITE);
        }
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1400, 600));

       // this.pack(); // Se ajusta al contenido visible
    }
    final boolean[] isPressed = new boolean[7];
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btn_Cerrar = new javax.swing.JButton();
        btn_Ordenes = new javax.swing.JButton();
        btn_Menu = new javax.swing.JButton();
        btn_Reclamos = new javax.swing.JButton();
        btn_Horarios = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Panel_Reclamos = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        comboTipo = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla_reclamos = new javax.swing.JTable();
        jScrollPane7 = new javax.swing.JScrollPane();
        tabla_reclamos4 = new javax.swing.JTable();
        jButton13 = new javax.swing.JButton();
        txtCliente7 = new javax.swing.JTextField();
        jButton14 = new javax.swing.JButton();
        txtCliente8 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        txtCliente9 = new javax.swing.JTextField();
        txtCliente10 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        txtCliente11 = new javax.swing.JTextField();
        jButton15 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        Panel_Horarios = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jTextField10 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jButton8 = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jTextField2 = new javax.swing.JTextField();

        Panel_ReporteVenta = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jComboBox5 = new javax.swing.JComboBox<>();
>>>>>>> 071a3b14831b64bc199aadc5064937c0c388e995
        Panel_Reportes = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        txtCliente1 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabla_reclamos1 = new javax.swing.JTable();
        jButton10 = new javax.swing.JButton();
        txtCliente2 = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        tabla_reclamos2 = new javax.swing.JTable();
        txtCliente3 = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        tabla_reclamos3 = new javax.swing.JTable();
        txtCliente4 = new javax.swing.JTextField();
        jButton11 = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        txtCliente6 = new javax.swing.JTextField();
        jButton12 = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("INICIO_SESION_GERENTE");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 2));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_Cerrar.setBackground(new java.awt.Color(0, 102, 102));
        btn_Cerrar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_Cerrar.setForeground(new java.awt.Color(255, 255, 255));
        btn_Cerrar.setText("Cerrar Sesión");
        btn_Cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CerrarActionPerformed(evt);
            }
        });
        jPanel2.add(btn_Cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, -1, -1));

        btn_Ordenes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_Ordenes.setForeground(new java.awt.Color(0, 89, 102));
        btn_Ordenes.setText("Ordenes");
        btn_Ordenes.setBorder(null);
        btn_Ordenes.setBorderPainted(false);
        btn_Ordenes.setContentAreaFilled(false);
        btn_Ordenes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_Ordenes.setDefaultCapable(false);
        btn_Ordenes.setFocusCycleRoot(true);
        btn_Ordenes.setFocusPainted(false);
        btn_Ordenes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_Ordenes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_OrdenesActionPerformed(evt);
            }
        });
        jPanel2.add(btn_Ordenes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 160, 30));
        //Main

        btn_Menu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_Menu.setForeground(new java.awt.Color(0, 89, 102));
        btn_Menu.setText("Reportes");
        btn_Menu.setBorder(null);
        btn_Menu.setBorderPainted(false);
        btn_Menu.setContentAreaFilled(false);
        btn_Menu.setDefaultCapable(false);
        btn_Menu.setFocusCycleRoot(true);
        btn_Menu.setFocusPainted(false);
        btn_Menu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MenuActionPerformed(evt);
            }
        });
        jPanel2.add(btn_Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 160, 30));

        btn_Reclamos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_Reclamos.setForeground(new java.awt.Color(0, 89, 102));
        btn_Reclamos.setText("Registro de Reclamos");
        btn_Reclamos.setBorder(null);
        btn_Reclamos.setBorderPainted(false);
        btn_Reclamos.setContentAreaFilled(false);
        btn_Reclamos.setDefaultCapable(false);
        btn_Reclamos.setFocusCycleRoot(true);
        btn_Reclamos.setFocusPainted(false);
        btn_Reclamos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_Reclamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ReclamosActionPerformed(evt);
            }
        });
        jPanel2.add(btn_Reclamos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 160, 30));

        btn_Horarios.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_Horarios.setForeground(new java.awt.Color(0, 89, 102));
        btn_Horarios.setText("Turnos y Horarios");
        btn_Horarios.setBorder(null);
        btn_Horarios.setBorderPainted(false);
        btn_Horarios.setContentAreaFilled(false);
        btn_Horarios.setDefaultCapable(false);
        btn_Horarios.setFocusCycleRoot(true);
        btn_Horarios.setFocusPainted(false);
        btn_Horarios.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_Horarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_HorariosActionPerformed(evt);
            }
        });
        jPanel2.add(btn_Horarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 160, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 89, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Starbucks Gerente");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 190, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 89, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Bienvenido(a) a");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 190, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 620));

        Panel_Reclamos.setFocusCycleRoot(true);
        Panel_Reclamos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(0, 102, 102));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("RECLAMOS");
        jPanel7.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 12, 1410, 40));

        Panel_Reclamos.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1450, 60));

        jPanel8.setBackground(new java.awt.Color(255, 252, 242));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Cliente :");
        jPanel8.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        jLabel4.setText("Fecha :");
        jPanel8.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        jLabel10.setText("Observación :");
        jPanel8.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));
        jPanel8.add(txtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 280, 140));

        comboTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel8.add(comboTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 210, -1));

        tabla_reclamos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Código", "Cliente", "Fecha", "Tipo de reclamo", "Descripción"
            }
        ));
        jScrollPane2.setViewportView(tabla_reclamos);
        if (tabla_reclamos.getColumnModel().getColumnCount() > 0) {
            tabla_reclamos.getColumnModel().getColumn(4).setHeaderValue("Descripción");
        }

        jPanel8.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, -1, 200));

        tabla_reclamos4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "DNI", "Cliente"
            }
        ));
        jScrollPane7.setViewportView(tabla_reclamos4);

        jPanel8.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 30, 330, 120));

        jButton13.setBackground(new java.awt.Color(0, 102, 102));
        jButton13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton13.setForeground(new java.awt.Color(255, 255, 255));
        jButton13.setText("Registrar Cliente");
        jPanel8.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 290, 150, -1));
        jPanel8.add(txtCliente7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 210, -1));

        jButton14.setBackground(new java.awt.Color(0, 102, 102));
        jButton14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton14.setForeground(new java.awt.Color(255, 255, 255));
        jButton14.setText("Buscar cliente");
        jPanel8.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, 110, -1));
        jPanel8.add(txtCliente8, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 190, 210, -1));

        jLabel28.setText("Cliente :");
        jPanel8.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 230, -1, -1));
        jPanel8.add(txtCliente9, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 230, 210, -1));
        jPanel8.add(txtCliente10, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 210, -1));

        jLabel29.setText("Tipo de Reclamo :");
        jPanel8.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));
        jPanel8.add(txtCliente11, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 210, -1));

        jButton15.setBackground(new java.awt.Color(0, 102, 102));
        jButton15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton15.setForeground(new java.awt.Color(255, 255, 255));
        jButton15.setText("Registrar Reclamo");
        jPanel8.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, -1, -1));

        jLabel23.setText("DNI del cliente :");
        jPanel8.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        jLabel24.setText("DNI del cliente :");
        jPanel8.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 190, -1, -1));

        Panel_Reclamos.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1400, 800));

        jPanel1.add(Panel_Reclamos, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 1400, 600));

        Panel_Horarios.setFocusCycleRoot(true);
        Panel_Horarios.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setBackground(new java.awt.Color(0, 102, 102));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("HORARIOS");
        jPanel9.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 12, 1400, 40));

        Panel_Horarios.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1450, 60));

        jPanel10.setBackground(new java.awt.Color(255, 252, 242));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setText("Empleado :");
        jPanel10.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel10.add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 120, -1));
        jPanel10.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 120, -1));

        jLabel19.setText("Fecha :");
        jPanel10.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        jLabel20.setText("Turno :");
        jPanel10.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 70, -1));

        jButton3.setBackground(new java.awt.Color(0, 102, 102));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Asignar");
        jPanel10.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, -1, -1));

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "DNI", "Empleado"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        jPanel10.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, 390, 150));

        jButton8.setBackground(new java.awt.Color(0, 102, 102));
        jButton8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Buscar empleado");
        jPanel10.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, -1, -1));

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Empleado", "Fecha", "Turno"
            }
        ));
        jScrollPane8.setViewportView(jTable4);
        if (jTable4.getColumnModel().getColumnCount() > 0) {
            jTable4.getColumnModel().getColumn(2).setHeaderValue("Turno");
        }

        jPanel10.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, 260));
        jPanel10.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 120, -1));

        Panel_Horarios.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1400, 800));

        jPanel1.add(Panel_Horarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 1400, 800));


        Panel_ReporteVenta.setFocusCycleRoot(true);
        Panel_ReporteVenta.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel13.setBackground(new java.awt.Color(0, 102, 102));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("REPORTE DE VENTAS");
        jPanel13.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 12, 660, 40));

        Panel_ReporteVenta.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1450, 60));

        jPanel14.setBackground(new java.awt.Color(255, 252, 242));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setText("Fecha :");
        jPanel14.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));
        jPanel14.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 160, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel14.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 160, -1));

        jLabel12.setText("Producto :");
        jPanel14.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, -1));

        jLabel13.setText("Cliente :");
        jPanel14.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));
        jPanel14.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 160, -1));

        jLabel14.setText("Empleado :");
        jPanel14.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, -1));

        jLabel15.setText("Precio :");
        jPanel14.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, -1, -1));
        jPanel14.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 160, -1));

        jButton2.setBackground(new java.awt.Color(0, 102, 102));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Generar");
        jPanel14.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Fecha", "Producto", "Cliente", "Empleado", "Precio"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel14.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, 560, 270));

        jButton5.setBackground(new java.awt.Color(0, 102, 102));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Buscar cliente");
        jPanel14.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 340, -1, -1));

        jButton6.setBackground(new java.awt.Color(0, 102, 102));
        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Buscar empleado");
        jPanel14.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 340, -1, -1));

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel14.add(jComboBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 160, -1));

        Panel_ReporteVenta.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1400, 800));

        jPanel1.add(Panel_ReporteVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 1400, 800));


        Panel_Reportes.setFocusCycleRoot(true);
        Panel_Reportes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel11.setBackground(new java.awt.Color(0, 102, 102));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("REPORTES");
        jPanel11.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 12, 1410, 40));

        Panel_Reportes.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1450, 60));

        jPanel12.setBackground(new java.awt.Color(255, 252, 242));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setText("Cliente :");
        jPanel12.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, -1));
        jPanel12.add(txtCliente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 210, -1));

        jLabel21.setText("Fecha :");
        jPanel12.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, -1));

        jLabel25.setText("Tipo de pago");
        jPanel12.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, -1, -1));

        tabla_reclamos1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "DNI", "Empleado"
            }
        ));
        jScrollPane4.setViewportView(tabla_reclamos1);

        jPanel12.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 190, 330, 120));

        jButton10.setBackground(new java.awt.Color(0, 102, 102));
        jButton10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setText("Buscar cliente");
        jPanel12.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, -1, -1));
        jPanel12.add(txtCliente2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 210, -1));

        tabla_reclamos2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Cliente", "Fecha", "Empleado", "Productos", "Tipo Pago"
            }
        ));
        jScrollPane5.setViewportView(tabla_reclamos2);

        jPanel12.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, 190));
        jPanel12.add(txtCliente3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 210, -1));

        tabla_reclamos3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "DNI", "Cliente"
            }
        ));
        jScrollPane6.setViewportView(tabla_reclamos3);

        jPanel12.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 30, 330, 120));
        jPanel12.add(txtCliente4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 210, -1));

        jButton11.setBackground(new java.awt.Color(0, 102, 102));
        jButton11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton11.setForeground(new java.awt.Color(255, 255, 255));
        jButton11.setText("Buscar empleado");
        jPanel12.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, -1, -1));

        jLabel26.setText("Empleado:");
        jPanel12.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, -1));
        jPanel12.add(txtCliente6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 210, -1));

        jButton12.setBackground(new java.awt.Color(0, 102, 102));
        jButton12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton12.setForeground(new java.awt.Color(255, 255, 255));
        jButton12.setText("Generar reporte");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel12.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, -1, -1));

        jLabel27.setText("Producto");
        jPanel12.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, -1, -1));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel12.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 210, -1));

        jLabel5.setText("DNI del Cliente :");
        jPanel12.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, -1));

        jLabel22.setText("DNI del Empleado :");
        jPanel12.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel12.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 210, -1));

        Panel_Reportes.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1400, 800));

        jPanel1.add(Panel_Reportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 1400, 600));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1400, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void cargarReclamos(){
        modeloTabla.setRowCount(0);
        
        for(Reclamo r : Principal.listaReclamos){
            modeloTabla.addRow(new Object[]{
                r.getCodigo(),
                r.getCliente(),
                r.getFecha(),
                r.getTipo(),
                r.getDescripcion()
            });
        }
    } 
    private void registrarReclamo(){
        
        
       
        String tipo = comboTipo.getSelectedItem().toString();
        String descripcion = txtDescripcion.getText();
        
       
        
        
        
        System.out.println("Registrado correctamente");
        cargarReclamos();
        limpiarCampos();
    }
    private void limpiarCampos(){
        
        
        
        comboTipo.setSelectedIndex(0);
        txtDescripcion.setText("");
        
    }
    private void btn_OrdenesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_OrdenesActionPerformed
        BotonPresionado(btn_Ordenes,new Color(243,247,237), isPressed, 0);
        activarUno(isPressed,0);
        System.out.println("Boton Ordenes presionado");
    }//GEN-LAST:event_btn_OrdenesActionPerformed

    private void btn_ReclamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ReclamosActionPerformed
        BotonPresionado(btn_Reclamos,new Color(243,247,237), isPressed, 1);
        activarUno(isPressed,1);
        System.out.println("Boton Reclamos presionado");
    }//GEN-LAST:event_btn_ReclamosActionPerformed

    private void btn_HorariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_HorariosActionPerformed
        BotonPresionado(btn_Horarios,new Color(243,247,237), isPressed, 2);
        activarUno(isPressed,2);
        System.out.println("Boton Horarios presionado");
    }//GEN-LAST:event_btn_HorariosActionPerformed

    private void btn_MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MenuActionPerformed
        BotonPresionado(btn_Menu,new Color(243,247,237), isPressed, 3);
        activarUno(isPressed,3);
        System.out.println("Boton Menu presionado");
    }//GEN-LAST:event_btn_MenuActionPerformed

    private void btn_CerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CerrarActionPerformed
        this.dispose();
        Principal.pantallaPrincipal.setVisible(true);
    }//GEN-LAST:event_btn_CerrarActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        registrarReclamo();
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    public void BotonPresionado(JButton boton, Color color, boolean[] isPressed, int array){
        isPressed[array] = true;
        boton.setBackground(color);
    }
    public void activarUno(boolean[] estados, int indiceActivo){
        JButton[] botones = {
            btn_Ordenes,
         
            btn_Reclamos,
            btn_Horarios,
        
            btn_Menu,
            
        };
        JPanel[] paneles = {
            
            Panel_Reclamos,
            Panel_Horarios,
            Panel_Reportes,
        };
        for(int i = 0;i<estados.length;i++){
            if(i == indiceActivo){
                estados[i] = (i== indiceActivo);
                paneles[i].setVisible(true);
            }else{
                estados[i] = false;
                botones[i].setBackground(Color.WHITE);
                paneles[i].setVisible(false);
            }
            
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel_Horarios;

    private javax.swing.JPanel Panel_Ordenes;
    private javax.swing.JPanel Panel_Reclamos;
    private javax.swing.JPanel Panel_ReporteVenta;
    private javax.swing.JPanel Panel_Reportes;
    private javax.swing.JButton btn_Cerrar;
    private javax.swing.JButton btn_Horarios;
    private javax.swing.JButton btn_Menu;
    private javax.swing.JButton btn_Ordenes;
    private javax.swing.JButton btn_Reclamos;
    private javax.swing.JComboBox<String> comboTipo;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton3;

    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;

    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;

    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;

    private javax.swing.JLabel jLabel8;

    private javax.swing.JLabel jLabel9;

    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTable tabla_reclamos;
    private javax.swing.JTable tabla_reclamos1;
    private javax.swing.JTable tabla_reclamos2;
    private javax.swing.JTable tabla_reclamos3;
    private javax.swing.JTable tabla_reclamos4;
    private javax.swing.JTextField txtCliente1;
    private javax.swing.JTextField txtCliente10;
    private javax.swing.JTextField txtCliente11;
    private javax.swing.JTextField txtCliente2;
    private javax.swing.JTextField txtCliente3;
    private javax.swing.JTextField txtCliente4;
    private javax.swing.JTextField txtCliente6;
    private javax.swing.JTextField txtCliente7;
    private javax.swing.JTextField txtCliente8;
    private javax.swing.JTextField txtCliente9;
    private javax.swing.JTextField txtDescripcion;
    // End of variables declaration//GEN-END:variables
}
