/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FORMULARIOS;
import CLASES.Cliente;
import CLASES.Empleado;
import CLASES.Horario;
import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JPanel;

import MAIN.Principal;
import CLASES.Reclamo;
import CLASES.Reporte;
import java.time.LocalDate;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author nobody
 */
public class Frm_Gerente extends javax.swing.JFrame {
    DefaultTableModel modeloTabla;
    DefaultTableModel tablaClientes;
    DefaultTableModel tablaHorarios;
    DefaultTableModel tablaEmpleados;
    DefaultTableModel tablaReporte;
    /**
     * Creates new form INICIO_SESION_GERENTE
     */
    int codigo = 0;
    public Frm_Gerente() {
        initComponents();
        this.setLocationRelativeTo(this);
        
        modeloTabla = (DefaultTableModel) tabla_reclamos.getModel();
        tablaClientes = (DefaultTableModel) tabla_Clientes.getModel();
        tablaHorarios = (DefaultTableModel) tabla_Horarios.getModel();
        tablaEmpleados = (DefaultTableModel) tabla_Empleados.getModel();
        tablaReporte = (DefaultTableModel) tabla_Reporte.getModel();
        Date fechaEspecifica = new Date(2025,7,15);
        Reclamo prueba = new Reclamo(codigo++, "Juan Pérez", fechaEspecifica, "Producto en mal estado", "El café llegó derramado y con la tapa rota.");
        Principal.listaReclamos.add(prueba);
        //
        cargarReclamos();
        JButton[] botones = {
            btn_Reclamos,
            btn_Horarios,
            btn_Reportes,
            
        };
        for (JButton btn : botones) {
            btn.setOpaque(true);
            btn.setBackground(Color.WHITE);
        }
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1400, 600));

       // this.pack(); // Se ajusta al contenido visible
    }
    final boolean[] isPressed = new boolean[3];
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btn_Cerrar = new javax.swing.JButton();
        btn_Reportes = new javax.swing.JButton();
        btn_Reclamos = new javax.swing.JButton();
        btn_Horarios = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Panel_Reclamos = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtObservacion = new javax.swing.JTextField();
        comboTipo = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla_reclamos = new javax.swing.JTable();
        jScrollPane7 = new javax.swing.JScrollPane();
        tabla_Clientes = new javax.swing.JTable();
        btnActualizar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        txtDniClienteRegistrar = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        txtNombreClienteRegistrar = new javax.swing.JTextField();
        txtDNICliente = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        txtNombreCliente = new javax.swing.JTextField();
        btn_RegistrarReclamo = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        DateChooser = new com.toedter.calendar.JDateChooser();
        btnRegistrarCliente = new javax.swing.JButton();
        Panel_Horarios = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        boxTurno = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        btnAsignar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabla_Empleados = new javax.swing.JTable();
        btnBuscarEmpleado = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        tabla_Horarios = new javax.swing.JTable();
        txtDniEmpleado = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        DateChooseHorario = new com.toedter.calendar.JDateChooser();
        txtEmpleadoNombre = new javax.swing.JTextField();
        btnActualizarHorario = new javax.swing.JButton();
        Panel_Reportes = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        btnBuscarClienteReporte = new javax.swing.JButton();
        txtClienteNombreReporte = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        tabla_Reporte = new javax.swing.JTable();
        txtDniClienteReporte = new javax.swing.JTextField();
        txtNombreEmpleadoReporte = new javax.swing.JTextField();
        jButton11 = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        txtDniEmpleadoReporte = new javax.swing.JTextField();
        btnGenerarReporte = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        boxTipoPago = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        boxProducto = new javax.swing.JComboBox<>();
        CheckTipo = new javax.swing.JCheckBox();
        CheckFecha = new javax.swing.JCheckBox();
        CheckCliente = new javax.swing.JCheckBox();
        CheckEmpleado = new javax.swing.JCheckBox();
        CheckProducto = new javax.swing.JCheckBox();
        DateChooserReporte = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("INICIO_SESION_GERENTE");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 2));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_Cerrar.setBackground(new java.awt.Color(0, 102, 102));
        btn_Cerrar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_Cerrar.setForeground(new java.awt.Color(255, 255, 255));
        btn_Cerrar.setText("Cerrar Sesión");
        btn_Cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CerrarActionPerformed(evt);
            }
        });
        jPanel2.add(btn_Cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, -1, -1));

        btn_Reportes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_Reportes.setForeground(new java.awt.Color(0, 89, 102));
        btn_Reportes.setText("Reportes");
        btn_Reportes.setBorder(null);
        btn_Reportes.setBorderPainted(false);
        btn_Reportes.setContentAreaFilled(false);
        btn_Reportes.setDefaultCapable(false);
        btn_Reportes.setFocusCycleRoot(true);
        btn_Reportes.setFocusPainted(false);
        btn_Reportes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_Reportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ReportesActionPerformed(evt);
            }
        });
        jPanel2.add(btn_Reportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 160, 30));

        btn_Reclamos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_Reclamos.setForeground(new java.awt.Color(0, 89, 102));
        btn_Reclamos.setText("Registro de Reclamos");
        btn_Reclamos.setBorder(null);
        btn_Reclamos.setBorderPainted(false);
        btn_Reclamos.setContentAreaFilled(false);
        btn_Reclamos.setDefaultCapable(false);
        btn_Reclamos.setFocusCycleRoot(true);
        btn_Reclamos.setFocusPainted(false);
        btn_Reclamos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_Reclamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ReclamosActionPerformed(evt);
            }
        });
        jPanel2.add(btn_Reclamos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 160, 30));

        btn_Horarios.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_Horarios.setForeground(new java.awt.Color(0, 89, 102));
        btn_Horarios.setText("Turnos y Horarios");
        btn_Horarios.setBorder(null);
        btn_Horarios.setBorderPainted(false);
        btn_Horarios.setContentAreaFilled(false);
        btn_Horarios.setDefaultCapable(false);
        btn_Horarios.setFocusCycleRoot(true);
        btn_Horarios.setFocusPainted(false);
        btn_Horarios.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_Horarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_HorariosActionPerformed(evt);
            }
        });
        jPanel2.add(btn_Horarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 160, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 89, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Starbucks Gerente");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 190, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 89, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Bienvenido(a) a");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 190, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 620));

        Panel_Reclamos.setFocusCycleRoot(true);
        Panel_Reclamos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(0, 102, 102));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("RECLAMOS");
        jPanel7.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 12, 1410, 40));

        Panel_Reclamos.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1450, 60));

        jPanel8.setBackground(new java.awt.Color(255, 252, 242));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Cliente :");
        jPanel8.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        jLabel4.setText("Fecha :");
        jPanel8.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        jLabel10.setText("Observación :");
        jPanel8.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));
        jPanel8.add(txtObservacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 280, 140));

        comboTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Calidad de Producto", "Servicio al Cliente", "Problemas en APP" }));
        jPanel8.add(comboTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 210, -1));

        tabla_reclamos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Cliente", "Fecha", "Tipo de reclamo", "Descripción"
            }
        ));
        jScrollPane2.setViewportView(tabla_reclamos);

        jPanel8.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, 650, 130));

        tabla_Clientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "DNI", "Cliente"
            }
        ));
        jScrollPane7.setViewportView(tabla_Clientes);

        jPanel8.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 40, 330, 120));

        btnActualizar.setBackground(new java.awt.Color(0, 102, 102));
        btnActualizar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizar.setText("Actualizar");
        jPanel8.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 320, 150, -1));

        btnBuscar.setBackground(new java.awt.Color(0, 102, 102));
        btnBuscar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("Buscar cliente");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel8.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, 110, -1));
        jPanel8.add(txtDniClienteRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 220, 210, -1));

        jLabel28.setText("Cliente :");
        jPanel8.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 260, -1, -1));
        jPanel8.add(txtNombreClienteRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 250, 210, -1));
        jPanel8.add(txtDNICliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 210, -1));

        jLabel29.setText("Tipo de Reclamo :");
        jPanel8.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        txtNombreCliente.setEnabled(false);
        jPanel8.add(txtNombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 210, -1));

        btn_RegistrarReclamo.setBackground(new java.awt.Color(0, 102, 102));
        btn_RegistrarReclamo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_RegistrarReclamo.setForeground(new java.awt.Color(255, 255, 255));
        btn_RegistrarReclamo.setText("Registrar Reclamo");
        btn_RegistrarReclamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RegistrarReclamoActionPerformed(evt);
            }
        });
        jPanel8.add(btn_RegistrarReclamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, -1, -1));

        jLabel23.setText("DNI del cliente :");
        jPanel8.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        jLabel24.setText("DNI del cliente :");
        jPanel8.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 220, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("Reclamos");
        jLabel11.setToolTipText("");
        jPanel8.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setText("Clientes");
        jLabel12.setToolTipText("");
        jPanel8.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 10, -1, -1));
        jPanel8.add(DateChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 200, -1));

        btnRegistrarCliente.setBackground(new java.awt.Color(0, 102, 102));
        btnRegistrarCliente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRegistrarCliente.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarCliente.setText("Registrar Cliente");
        btnRegistrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarClienteActionPerformed(evt);
            }
        });
        jPanel8.add(btnRegistrarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 290, 150, -1));

        Panel_Reclamos.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1390, 800));

        jPanel1.add(Panel_Reclamos, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 1400, 600));

        Panel_Horarios.setFocusCycleRoot(true);
        Panel_Horarios.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setBackground(new java.awt.Color(0, 102, 102));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("HORARIOS");
        jPanel9.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 12, 1400, 40));

        Panel_Horarios.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1450, 60));

        jPanel10.setBackground(new java.awt.Color(255, 252, 242));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setText("Empleado :");
        jPanel10.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        boxTurno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mañana", "Tarde", "Noche" }));
        jPanel10.add(boxTurno, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 120, -1));

        jLabel19.setText("Fecha :");
        jPanel10.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        jLabel20.setText("Turno :");
        jPanel10.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 70, -1));

        btnAsignar.setBackground(new java.awt.Color(0, 102, 102));
        btnAsignar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAsignar.setForeground(new java.awt.Color(255, 255, 255));
        btnAsignar.setText("Asignar");
        btnAsignar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignarActionPerformed(evt);
            }
        });
        jPanel10.add(btnAsignar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, -1, -1));

        tabla_Empleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "DNI", "Empleado"
            }
        ));
        jScrollPane3.setViewportView(tabla_Empleados);

        jPanel10.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 50, 390, 150));

        btnBuscarEmpleado.setBackground(new java.awt.Color(0, 102, 102));
        btnBuscarEmpleado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBuscarEmpleado.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarEmpleado.setText("Buscar empleado");
        btnBuscarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarEmpleadoActionPerformed(evt);
            }
        });
        jPanel10.add(btnBuscarEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, -1, -1));

        tabla_Horarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Empleado", "Fecha", "Turno"
            }
        ));
        jScrollPane8.setViewportView(tabla_Horarios);
        if (tabla_Horarios.getColumnModel().getColumnCount() > 0) {
            tabla_Horarios.getColumnModel().getColumn(2).setHeaderValue("Turno");
        }

        jPanel10.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 500, 260));
        jPanel10.add(txtDniEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 120, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Horarios");
        jPanel10.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("Empleados");
        jPanel10.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, -1, -1));
        jPanel10.add(DateChooseHorario, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 130, -1));

        txtEmpleadoNombre.setEnabled(false);
        jPanel10.add(txtEmpleadoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 120, -1));

        btnActualizarHorario.setBackground(new java.awt.Color(0, 102, 102));
        btnActualizarHorario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnActualizarHorario.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizarHorario.setText("Actualizar");
        btnActualizarHorario.setToolTipText("");
        btnActualizarHorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarHorarioActionPerformed(evt);
            }
        });
        jPanel10.add(btnActualizarHorario, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 220, -1, -1));

        Panel_Horarios.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1400, 800));

        jPanel1.add(Panel_Horarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 1400, 800));

        Panel_Reportes.setFocusCycleRoot(true);
        Panel_Reportes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel11.setBackground(new java.awt.Color(0, 102, 102));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("REPORTES");
        jPanel11.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 12, 1410, 40));

        Panel_Reportes.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1450, 60));

        jPanel12.setBackground(new java.awt.Color(255, 252, 242));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setText("Cliente :");
        jPanel12.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, -1));

        jLabel21.setText("Fecha :");
        jPanel12.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, -1));

        jLabel25.setText("Tipo de pago");
        jPanel12.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, -1, -1));

        btnBuscarClienteReporte.setBackground(new java.awt.Color(0, 102, 102));
        btnBuscarClienteReporte.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBuscarClienteReporte.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarClienteReporte.setText("Buscar cliente");
        btnBuscarClienteReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarClienteReporteActionPerformed(evt);
            }
        });
        jPanel12.add(btnBuscarClienteReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, -1, -1));

        txtClienteNombreReporte.setEnabled(false);
        jPanel12.add(txtClienteNombreReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 210, -1));

        tabla_Reporte.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Cliente", "Fecha", "Empleado", "Productos", "Tipo Pago"
            }
        ));
        jScrollPane5.setViewportView(tabla_Reporte);

        jPanel12.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 40, -1, 410));

        txtDniClienteReporte.setEnabled(false);
        jPanel12.add(txtDniClienteReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 210, -1));

        txtNombreEmpleadoReporte.setEnabled(false);
        jPanel12.add(txtNombreEmpleadoReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 210, -1));

        jButton11.setBackground(new java.awt.Color(0, 102, 102));
        jButton11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton11.setForeground(new java.awt.Color(255, 255, 255));
        jButton11.setText("Buscar empleado");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel12.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 170, -1, -1));

        jLabel26.setText("Empleado:");
        jPanel12.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, -1));

        txtDniEmpleadoReporte.setEnabled(false);
        jPanel12.add(txtDniEmpleadoReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 210, -1));

        btnGenerarReporte.setBackground(new java.awt.Color(0, 102, 102));
        btnGenerarReporte.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnGenerarReporte.setForeground(new java.awt.Color(255, 255, 255));
        btnGenerarReporte.setText("Generar reporte");
        btnGenerarReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarReporteActionPerformed(evt);
            }
        });
        jPanel12.add(btnGenerarReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, -1, -1));

        jLabel27.setText("Producto");
        jPanel12.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, -1, -1));

        boxTipoPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Efectivo", "Tarjeta" }));
        boxTipoPago.setEnabled(false);
        jPanel12.add(boxTipoPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 210, -1));

        jLabel5.setText("DNI del Cliente :");
        jPanel12.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, -1));

        jLabel22.setText("DNI del Empleado :");
        jPanel12.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, -1));

        boxProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cafe", "Pan" }));
        boxProducto.setEnabled(false);
        jPanel12.add(boxProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 210, -1));

        CheckTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckTipoActionPerformed(evt);
            }
        });
        jPanel12.add(CheckTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, -1, -1));

        CheckFecha.setActionCommand("");
        CheckFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckFechaActionPerformed(evt);
            }
        });
        jPanel12.add(CheckFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 40, -1, -1));

        CheckCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckClienteActionPerformed(evt);
            }
        });
        jPanel12.add(CheckCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, -1, -1));

        CheckEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckEmpleadoActionPerformed(evt);
            }
        });
        jPanel12.add(CheckEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, -1, -1));

        CheckProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckProductoActionPerformed(evt);
            }
        });
        jPanel12.add(CheckProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, -1, -1));

        DateChooserReporte.setEnabled(false);
        jPanel12.add(DateChooserReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 210, -1));

        Panel_Reportes.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1400, 800));

        jPanel1.add(Panel_Reportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 1400, 600));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1400, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void cargarReclamos(){
        modeloTabla.setRowCount(0);
        
        for(Reclamo r : Principal.listaReclamos){
            modeloTabla.addRow(new Object[]{
                r.getCodigo(),
                r.getDNICliente(),
                r.getFecha(),
                r.getTipo(),
                r.getObservacion()
            });
        }
    } 
    private void cargarClientes(){
        tablaClientes.setRowCount(0);
        
        for(Cliente r : Principal.listaClientes){
            tablaClientes.addRow(new Object[]{
                r.getDNI(),
                r.getNombreCliente(),
            });
        }
    }
    private void cargarEmpleados(){
        tablaEmpleados.setRowCount(0);
        
        for(Empleado r : Principal.listaEmpleados){
            tablaEmpleados.addRow(new Object[]{
                r.getDNI(),
                r.getNombreEmpleado(),
            });
        }
    }
    private void cargarHorarios(){
        tablaHorarios.setRowCount(0);
        
        for(Horario r : Principal.listaHorarios){
            tablaHorarios.addRow(new Object[]{
                r.getDNIEmpleado(),
                r.getFecha(),
                r.getTurno(),
            });
        }
    } 
    private void registrarReclamo(){
        Date fecha = DateChooser.getDate();
        String DNI = txtDNICliente.getText();
        String tipo = comboTipo.getSelectedItem().toString();
        String observacion = txtObservacion.getText();
        
        Principal.listaReclamos.add(new Reclamo(codigo++, DNI, fecha, tipo, observacion));
        System.out.println("Registrado Reclamo correctamente");
        
        cargarReclamos();
        limpiarCampos();
    }
    private void registrarCliente(){
        String DNI = txtDniClienteRegistrar.getText();
        String Nombre = txtNombreClienteRegistrar.getText();
        
        Principal.listaClientes.add(new Cliente(DNI, Nombre));
        System.out.println("Registrado Cliente correctamente");
        cargarClientes();
        limpiarCamposCliente();
    }
    private void registrarHorario(){
        String DNI = txtDniEmpleado.getText();
        Date fecha = DateChooseHorario.getDate();
        String turno = boxTurno.getSelectedItem().toString();
        
        Principal.listaHorarios.add(new Horario(DNI, fecha, turno));
        System.out.println("Horario Cliente correctamente");
        cargarHorarios();
        limpiarCamposHorarios();
    }
    private void limpiarCampos(){
        txtDNICliente.setText("");
        txtNombreCliente.setText("");
        comboTipo.setSelectedIndex(0);
        txtObservacion.setText("");  
    }
    private void limpiarCamposCliente(){
        txtDniClienteRegistrar.setText("");
        txtNombreClienteRegistrar.setText("");   
    }
    private void limpiarCamposHorarios(){
        txtDniEmpleado.setText("");
        boxTurno.setSelectedIndex(0);
    }
    private void btn_ReclamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ReclamosActionPerformed
        BotonPresionado(btn_Reclamos,new Color(243,247,237), isPressed, 0);
        activarUno(isPressed,0);
        System.out.println("Boton Reclamos presionado");
    }//GEN-LAST:event_btn_ReclamosActionPerformed

    private void btn_HorariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_HorariosActionPerformed
        BotonPresionado(btn_Horarios,new Color(243,247,237), isPressed, 1);
        activarUno(isPressed,1);
        System.out.println("Boton Horarios presionado");
    }//GEN-LAST:event_btn_HorariosActionPerformed

    private void btn_ReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ReportesActionPerformed
        BotonPresionado(btn_Reportes,new Color(243,247,237), isPressed, 2);
        activarUno(isPressed,2);
        System.out.println("Boton Reportes presionado");
    }//GEN-LAST:event_btn_ReportesActionPerformed

    private void btn_CerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CerrarActionPerformed
        this.dispose();
        Principal.pantallaPrincipal.setVisible(true);
    }//GEN-LAST:event_btn_CerrarActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        registrarReclamo();
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnGenerarReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarReporteActionPerformed
        tablaReporte.setRowCount(0);
        for (Reporte r : Principal.listaReportes) {
            boolean cumpleFiltros = true;
                if(CheckFecha.isSelected()){
                    Date fechaSeleccionada = DateChooserReporte.getDate();
                    if(!r.getFecha().equals(fechaSeleccionada)){
                        cumpleFiltros = false;
                    }
                }
                if(CheckCliente.isSelected()){
                    String NombreCliente = txtClienteNombreReporte.getText();
                    if(!r.getCliente().contains(NombreCliente)){
                        cumpleFiltros = false;
                    }
                }
                if(CheckEmpleado.isSelected()){
                    String NombreEmpleado = txtNombreEmpleadoReporte.getText();
                    if(!r.getEmpleado().contains(NombreEmpleado)){
                        cumpleFiltros = false;
                    }
                }
                if(CheckProducto.isSelected()){
                    String producto = boxProducto.getSelectedItem().toString();
                    if(!r.getProducto().contains(producto)){
                        cumpleFiltros = false;
                    }
                }
                if(CheckTipo.isSelected()){
                    String tipo = boxTipoPago.getSelectedItem().toString();
                    if(!r.getTipoPago().contains(tipo)){
                        cumpleFiltros = false;
                    }
                }
                if(cumpleFiltros){
                    tablaReporte.addRow(new Object[]{
                        r.getCliente(),
                        r.getFecha(),
                        r.getEmpleado(),
                        r.getProducto(),
                        r.getTipoPago(),
                    });
                }
        }
        if(tablaReporte.getRowCount()==0){
            JOptionPane.showMessageDialog(null, "No se encontraro resultados.");
        }
                
    }//GEN-LAST:event_btnGenerarReporteActionPerformed

    private void btn_RegistrarReclamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RegistrarReclamoActionPerformed
        if(txtNombreCliente.getText().equals("") && txtObservacion.getText().equals("")){
            JOptionPane.showMessageDialog(null,"LLENE LOS DATOS ");
        }else{
            registrarReclamo();
        }

    }//GEN-LAST:event_btn_RegistrarReclamoActionPerformed

    private void btnRegistrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarClienteActionPerformed
        registrarCliente();
    }//GEN-LAST:event_btnRegistrarClienteActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String dniBuscado = txtDNICliente.getText();
        boolean encontrado = false;
        for(Cliente r : Principal.listaClientes){
            if(r.getDNI().equals(dniBuscado)){
                JOptionPane.showMessageDialog(null,"CLIENTE ENCONTRADO " + r.getDNI());
                txtNombreCliente.setText(r.getNombreCliente());
                encontrado = true;
                break;
            }
        }
        if (!encontrado){
            JOptionPane.showMessageDialog(null,"CLIENTE NO ENCONTRADO ");
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnAsignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarActionPerformed
        if(txtEmpleadoNombre.getText().equals("")){
            JOptionPane.showMessageDialog(null,"LLENE LOS DATOS ");
        }else{
            registrarHorario();
        }
    }//GEN-LAST:event_btnAsignarActionPerformed

    private void btnActualizarHorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarHorarioActionPerformed
        cargarEmpleados();
    }//GEN-LAST:event_btnActualizarHorarioActionPerformed

    private void btnBuscarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarEmpleadoActionPerformed
        String dniBuscado = txtDniEmpleado.getText();
        boolean encontrado = false;
        for(Empleado r : Principal.listaEmpleados){
            if(r.getDNI().equals(dniBuscado)){
                JOptionPane.showMessageDialog(null,"EMPLEADO ENCONTRADO " + r.getDNI());
                txtEmpleadoNombre.setText(r.getNombreEmpleado());
                encontrado = true;
                break;
            }
        }
        if (!encontrado){
            JOptionPane.showMessageDialog(null,"EMPLEADO NO ENCONTRADO ");
        }
    }//GEN-LAST:event_btnBuscarEmpleadoActionPerformed

    private void CheckClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckClienteActionPerformed
        if(CheckCliente.isSelected()){
            txtDniClienteReporte.setEnabled(true);
        }else{
             txtDniClienteReporte.setEnabled(false);
        }
    }//GEN-LAST:event_CheckClienteActionPerformed

    private void CheckFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckFechaActionPerformed
        if(CheckFecha.isSelected()){
            DateChooserReporte.setEnabled(true);
        }else{
             DateChooserReporte.setEnabled(false);
        }


    }//GEN-LAST:event_CheckFechaActionPerformed

    private void CheckEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckEmpleadoActionPerformed
        if(CheckEmpleado.isSelected()){
            txtDniEmpleadoReporte.setEnabled(true);
        }else{
             txtDniEmpleadoReporte.setEnabled(false);
        }
    }//GEN-LAST:event_CheckEmpleadoActionPerformed

    private void CheckProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckProductoActionPerformed
        if(CheckProducto.isSelected()){
            boxProducto.setEnabled(true);
        }else{
             boxProducto.setEnabled(false);
        }
    }//GEN-LAST:event_CheckProductoActionPerformed

    private void CheckTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckTipoActionPerformed
        if(CheckTipo.isSelected()){
            boxTipoPago.setEnabled(true);
        }else{
             boxTipoPago.setEnabled(false);
        }
    }//GEN-LAST:event_CheckTipoActionPerformed

    private void btnBuscarClienteReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarClienteReporteActionPerformed
        String dniBuscado = txtDniClienteReporte.getText();
        boolean encontrado = false;
        for(Cliente r : Principal.listaClientes){
            if(r.getDNI().equals(dniBuscado)){
                JOptionPane.showMessageDialog(null,"CLIENTE ENCONTRADO " + r.getDNI());
                txtClienteNombreReporte.setText(r.getNombreCliente());
                encontrado = true;
                break;
            }
        }
        if (!encontrado){
            JOptionPane.showMessageDialog(null,"CLIENTE NO ENCONTRADO ");
        }
    }//GEN-LAST:event_btnBuscarClienteReporteActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        String dniBuscado = txtDniEmpleadoReporte.getText();
        boolean encontrado = false;
        for(Empleado r : Principal.listaEmpleados){
            if(r.getDNI().equals(dniBuscado)){
                JOptionPane.showMessageDialog(null,"EMPLEADO ENCONTRADO " + r.getDNI());
                txtNombreEmpleadoReporte.setText(r.getNombreEmpleado());
                encontrado = true;
                break;
            }
        }
        if (!encontrado){
            JOptionPane.showMessageDialog(null,"EMPLEADO NO ENCONTRADO ");
        }
    }//GEN-LAST:event_jButton11ActionPerformed
    
    public void BotonPresionado(JButton boton, Color color, boolean[] isPressed, int array){
        isPressed[array] = true;
        boton.setBackground(color);
    }
    public void activarUno(boolean[] estados, int indiceActivo){
        JButton[] botones = {         
            btn_Reclamos,
            btn_Horarios,
            btn_Reportes,
            
        };
        JPanel[] paneles = {
            Panel_Reclamos,
            Panel_Horarios,
            Panel_Reportes,
        };
        for(int i = 0;i<estados.length;i++){
            if(i == indiceActivo){
                estados[i] = (i== indiceActivo);
                paneles[i].setVisible(true);
            }else{
                estados[i] = false;
                botones[i].setBackground(Color.WHITE);
                paneles[i].setVisible(false);
            }
            
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CheckCliente;
    private javax.swing.JCheckBox CheckEmpleado;
    private javax.swing.JCheckBox CheckFecha;
    private javax.swing.JCheckBox CheckProducto;
    private javax.swing.JCheckBox CheckTipo;
    private com.toedter.calendar.JDateChooser DateChooseHorario;
    private com.toedter.calendar.JDateChooser DateChooser;
    private com.toedter.calendar.JDateChooser DateChooserReporte;
    private javax.swing.JPanel Panel_Horarios;
    private javax.swing.JPanel Panel_Reclamos;
    private javax.swing.JPanel Panel_Reportes;
    private javax.swing.JComboBox<String> boxProducto;
    private javax.swing.JComboBox<String> boxTipoPago;
    private javax.swing.JComboBox<String> boxTurno;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnActualizarHorario;
    private javax.swing.JButton btnAsignar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnBuscarClienteReporte;
    private javax.swing.JButton btnBuscarEmpleado;
    private javax.swing.JButton btnGenerarReporte;
    private javax.swing.JButton btnRegistrarCliente;
    private javax.swing.JButton btn_Cerrar;
    private javax.swing.JButton btn_Horarios;
    private javax.swing.JButton btn_Reclamos;
    private javax.swing.JButton btn_RegistrarReclamo;
    private javax.swing.JButton btn_Reportes;
    private javax.swing.JComboBox<String> comboTipo;
    private javax.swing.JButton jButton11;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTable tabla_Clientes;
    private javax.swing.JTable tabla_Empleados;
    private javax.swing.JTable tabla_Horarios;
    private javax.swing.JTable tabla_Reporte;
    private javax.swing.JTable tabla_reclamos;
    private javax.swing.JTextField txtClienteNombreReporte;
    private javax.swing.JTextField txtDNICliente;
    private javax.swing.JTextField txtDniClienteRegistrar;
    private javax.swing.JTextField txtDniClienteReporte;
    private javax.swing.JTextField txtDniEmpleado;
    private javax.swing.JTextField txtDniEmpleadoReporte;
    private javax.swing.JTextField txtEmpleadoNombre;
    private javax.swing.JTextField txtNombreCliente;
    private javax.swing.JTextField txtNombreClienteRegistrar;
    private javax.swing.JTextField txtNombreEmpleadoReporte;
    private javax.swing.JTextField txtObservacion;
    // End of variables declaration//GEN-END:variables
}
